router id 10.0.0.1;

ipv4 table noncn4;
ipv6 table noncn6;

protocol device {
}

protocol static noncn_static4 {
    ipv4 {
        table noncn4;
        import all;
    };

    include "/etc/bird/noncn4.routes";
}

protocol static noncn_static6 {
    ipv6 {
        table noncn6;
        import all;
    };

    include "/etc/bird/noncn6.routes";
}

filter export_noncn {
    if source = RTS_STATIC then accept;
    reject;
}

template bgp routeros_client {
    local 10.0.0.1 as 65000;
    direct;

    ipv4 {
        table noncn4;
        import none;
        export filter export_noncn;
        next hop self yes;
        next hop address 10.0.0.1;
    };

    ipv6 {
        table noncn6;
        import none;
        export filter export_noncn;
        next hop self yes;
        next hop address fd00::1;
    };
}

protocol bgp routeros1 from routeros_client {
    neighbor 10.0.0.2 as 65000;
}
